name: Nightly Deploy

on:
  schedule:
    - cron: '0 0 * * *'  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Build Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Install Project Requirements
      run: |
        pip install -r src/requirements.txt

    - name: Build Project
      run: |
        python -m build

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: NeroEditor-Nightly
        path: dist/
